In [1]:
import tensorflow_hub as hub
import pandas as pd
import tensorflow_text as text

In [2]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [3]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [4]:
text = ["I love food", "i love using python to code"]
text_preprocess = bert_preprocess_model(text)
text_preprocess.keys()

dict_keys(['input_mask', 'input_word_ids', 'input_type_ids'])

In [5]:
text_preprocess['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [6]:
text_preprocess['input_type_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [7]:
text_preprocess['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  1045,  2293,  2833,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

BERT uses CLS as a special token at the begining of each sentence, whereas SEP as a special token to end sentence

In [8]:
bert_model = hub.KerasLayer(encoder_url)

In [9]:
bert_result = bert_model(text_preprocess)
bert_result.keys()

dict_keys(['sequence_output', 'default', 'pooled_output', 'encoder_outputs'])

In [10]:
bert_result['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.17053258,  0.07656218, -0.0529479 , ..., -0.03142276,
           0.146555  ,  0.04733908],
         [ 0.55632603,  1.1137154 , -0.04405625, ...,  0.20375198,
           0.85449004,  0.0286283 ],
         [ 1.2446699 ,  0.92379415,  0.7588304 , ...,  0.18353137,
           0.90066725, -0.19001567],
         ...,
         [ 0.07289388, -0.07051979,  0.8278925 , ...,  0.27346754,
          -0.29493064, -0.15819326],
         [-0.0284231 , -0.12373298,  0.7025099 , ...,  0.33890146,
          -0.21290468, -0.24357808],
         [ 0.11734409, -0.0568675 ,  0.7036069 , ...,  0.6309669 ,
          -0.5237893 , -0.29526412]],
 
        [[ 0.16551054,  0.01441755, -0.06977063, ...,  0.00849456,
           0.07588569,  0.04461527],
         [ 0.6850365 ,  0.67590827, -0.31417996, ...,  0.5760351 ,
           0.8159324 ,  0.1546705 ],
         [ 1.3470492 ,  0.55638677, -0.12674306, ...,  0.52555263,
           0.32282355,  0.08

In [11]:
bert_result['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.2050471 ,  0.3800774 , -0.08654463, ..., -0.10243104,
          0.14957213,  0.13733971],
        [ 0.35241675,  0.18065163, -0.37599528, ..., -0.35386142,
          0.57992494,  0.11431654],
        [ 1.3531929 ,  0.48877785,  0.5085977 , ..., -0.20158479,
          0.52281815,  0.04308312],
        ...,
        [ 0.373787  ,  0.3743812 ,  0.2553571 , ...,  0.29722846,
         -0.07760819, -0.06020823],
        [ 0.33119777,  0.27041003,  0.1883961 , ...,  0.34111768,
         -0.072488  , -0.11211058],
        [-0.02988008,  0.05010987,  0.23346356, ...,  0.50569975,
         -0.11163453, -0.18019423]],

       [[ 0.17356844,  0.29934838, -0.25228232, ..., -0.06422054,
          0.17353147,  0.68430185],
        [ 0.8205828 ,  0.13964833, -0.51786923, ..., -0.04500287,
          0.38949296,  0.61271495],
        [ 0.9550675 ,  1.0886539 , -0.1222956 , ...,  0.22304645,
          0.20819655,  0.47375524],
        ...,

In [12]:
bert_result['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8265146 , -0.24179183,  0.44840458, ...,  0.28981814,
        -0.62344337,  0.88241076],
       [-0.8736644 , -0.453239  , -0.62275356, ..., -0.50374335,
        -0.6993199 ,  0.9052958 ]], dtype=float32)>